version = 0.1

[default.global.parameters]
stack_name = "SCI_API"
region = "eu-west-1"

[default.sync.parameters]
template_file = "template.yaml"
dependency_layer = false
use_container = true
watch = true
