Transform: AWS::Serverless-2016-10-31
Resources:
  SciBackend:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: SciBackend
      CodeUri: src
      Handler: app.app.lambda_handler
      Runtime: python3.9
      MemorySize: 256
      Timeout: 20
      Tracing: Active
      Environment:
        Variables:
          SCIDATA_TABLE_NAME: !Ref SciData
          SCIDATA_TABLE_ARN: !GetAtt SciData.Arn
          AWS_CODEGURU_PROFILER_GROUP_NAME: SciDataProfilingGroup
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SciData
      Events:
        SciApiPOSTdata:
          Type: Api
          Properties:
            Path: /data
            Method: POST
            RestApiId: !Ref SciApi
        SciApiGETdata:
          Type: Api
          Properties:
            Path: /data
            Method: GET
            RestApiId: !Ref SciApi
        SciApiPOSTdatamappingfull:
          Type: Api
          Properties:
            Path: /data/mapping/full
            Method: POST
            RestApiId: !Ref SciApi
        SciApiGETdatamappingfull:
          Type: Api
          Properties:
            Path: /data/mapping/full
            Method: GET
            RestApiId: !Ref SciApi
  loginLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${SciBackend}
  SciApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub
        - ${ResourceName} From Stack ${AWS::StackName}
        - ResourceName: SciApi
      StageName: Prod
      DefinitionBody:
        openapi: '3.0'
        info: {}
        paths:
          /data:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SciBackend.Arn}/invocations
              responses: {}
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SciBackend.Arn}/invocations
              responses: {}
          /data/mapping/full:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SciBackend.Arn}/invocations
              responses: {}
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SciBackend.Arn}/invocations
              responses: {}
          /data/products:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SciBackend.Arn}/invocations
              responses: {}
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
      Cors:
        MaxAge: 5
  SciData:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
        - AttributeName: ParentId
          AttributeType: S
        - AttributeName: SampleId
          AttributeType: S
        - AttributeName: SubsampleId
          AttributeType: S
        - AttributeName: MeasurementId
          AttributeType: S
        - AttributeName: ProductId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: SampleId
          KeyType: HASH
        - AttributeName: Id
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: SubsampleIdx
          KeySchema: 
            - AttributeName: SampleId
              KeyType: HASH
            - AttributeName: SubsampleId
              KeyType: RANGE        
          Projection: 
            ProjectionType: KEYS_ONLY
        - IndexName: ParentIdx
          KeySchema: 
            - AttributeName: SampleId
              KeyType: HASH
            - AttributeName: ParentId
              KeyType: RANGE        
          Projection: 
            ProjectionType: KEYS_ONLY
        - IndexName: MeasurementIdx
          KeySchema: 
            - AttributeName: SampleId
              KeyType: HASH
            - AttributeName: MeasurementId
              KeyType: RANGE        
          Projection: 
            ProjectionType: KEYS_ONLY
        - IndexName: ProductIdx
          KeySchema: 
            - AttributeName: SampleId
              KeyType: HASH
            - AttributeName: ProductId
              KeyType: RANGE        
          Projection: 
            ProjectionType: KEYS_ONLY
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES